@startuml
' Definición de clases con estereotipos personalizados
class Cliente <<Usuario>> {
  nombre : String
  correo : String
}

class EspacioParqueo <<EspacioParqueo>> {
  tipo : String
  disponible : Boolean
}

class Reservacion <<Reserva>> {
  fechaInicio : Date
  fechaFin : Date
}
@enduml

