@startuml
object Cliente {
    id = 1
    nombre = "Juan Pérez"
    telefono = "123456789"
}

object Vehiculo {
    placa = "ABC123"
    marca = "Toyota"
    modelo = "Corolla"
}

object Ticket {
    codigo = 1001
    fechaHoraEntrada = "2024-11-08 08:00"
    fechaHoraSalida = "2024-11-08 10:00"
}

Cliente -- Vehiculo
Cliente -- Ticket
@enduml
