@startuml
class Cliente {
    -id: int
    -nombre: string
    -telefono: string
    +registrarCliente()
    +actualizarDatos()
}

class Vehiculo {
    -placa: string
    -marca: string
    -modelo: string
    +registrarVehiculo()
}

class Ticket {
    -codigo: int
    -fechaHoraEntrada: datetime
    -fechaHoraSalida: datetime
    +emitirTicket()
    +calcularPago()
}

Cliente "1" -- "N" Vehiculo
Cliente "1" -- "N" Ticket
@enduml
